Fixed compatibility with Linux and improved tests
hazdryx/FastBitmap pull request #3
Opened 2021-05-06 09:12 UTC by Igneom

Managed to fix the issues discussed on #2, it possibly also increased the performance of object creation.

2021-05-06 12:15 UTC, hazdryx requested changes
Couple changes I would suggest:
- Use class names instead of `var` so it matches the rest of the code base.
- When you attempt to copy data from the Image you cast it to a Bitmap, but it is not guaranteed to be a Bitmap. You can use `Bitmap bmp = new Bitmap(image);` instead.
- Move each testing class to their own file so the base class file is less cluttered.

2021-05-07 06:12 UTC, Igneom commented
From what I understood by reading the Image class API, there's only two classes that derive from it, Bitmap and Metafile. Bitmap for pretty much any image file, png, bmp, jpg, etc. And Metafile for WMF or EMF files, which to be honest, never seen one of them, and judging by the implementation, FastBitmap may not be able to handle them properly. Plus, even though the Image class is an abstract class, you can't inherit from it, because the constructor is set as internal, so the only classe to be able to inherit from Image, is Bitmap, and Metafile, or some class that may show up in the future inside the same assembly. There's also the fact that Bitmap class, doesn't represent only a bmp file, just seems to be the literal mapping of the bits inside an image, on yx coordinates, and what I personally find weird, is that most of the code that I see, regarding image manipulation, always uses Image instead of Bitmap, with a direct conversion to Bitmap inside the code, when it could've been Bitmap from the start, and the only issue would be lack of support for Metafile, which most code is not made to handle it anyway, and any class inherited from Image class, would have to be inherited from Bitmap class instead.

Also, another issue, if I change it to `Bitmap bmp = new Bitmap(image);`, some of the Get tests fail on Windows and Linux, with incorrect values. At first I thought that there was some issue due to the original image passed in the constructor being collected by GC, and that there may be something being kept from that object, which would be a way bigger issue. But with the casting implementation, and disposing it inside the constructor, and/or disposing the original image outside, right after the FastBitmap object was created, all the tests passed normally on both platforms. So, there's something inside the Bitmap constructor, that messes up the pixel values slightly, either some compression happening or it being converted to another PixelFormat, which doesn't happen when it's casted, which in this context, I also believe it's the proper way to do, since there's no need to create a new object, since it's only accessing the data from the passed Image object in order to copy it, and casting doesn't allocate new memory, just treats the object as if it was another object.

I almost changed the constructor parameter to Bitmap, instead of Image, which would remove the need to cast it, and in my opinion be more consistent with the intentions of the library, but went back in this decision, since this seems out of context of this pull request, and a decision that I believe you yourself need to make, since you're the creator of the library.

2021-05-07 10:51 UTC, hazdryx approved these changes

2021-05-07 11:01 UTC, hazdryx commented
That makes a lot of sense then, and I will probably change the parameter to Bitmap in the future. I have a feeling it probably is changing the color data, which FastBitmap is not able to handle.

2021-05-07 11:02 UTC, merged